### ISSUE TITLE
Shop still having issues..

### ISSUE THREAD

**Issue by EngineerBean** [beelitzs/ConquestPlugin#112]
Purchase made in game, no item recieved.
No errors from extender command line output.
may need debug trace as nothing shows as per normal successful output

**Comment by proelitem** [comment]
Issue is still occurring. Started digging up wrapping my head around the program... I found odd that there's two commands launching: /add comp and /add ingot and they don't seem to be implemented properly.. maybe I just didn't get it yet. 

With the new system in place, are these commands even working? Will the server extender deliver?  We know that until recently, any types of commands wouldn't register.. maybe these are just ignored by the system as simple chat.  

I may be wrong, but any clues/theories serving as leads to fix the bug would help.
